### ISSUE TITLE
Invalid ASCII character error in logs

### ISSUE THREAD

**Issue by mikewheaton** [L-A/Little-Jekyll#7]
First of all, thanks for making this!

I just ran into a minor issue I wanted to make you aware of. When I start the server using Little Jekyll I get an error in the logs: 

![image](https://cloud.githubusercontent.com/assets/1382445/15660097/f3f87ffe-268b-11e6-8fef-fbab4580d636.png)

This doesn't occur when I use the typical `jekyll serve` command:

![image](https://cloud.githubusercontent.com/assets/1382445/15660093/e4a47418-268b-11e6-8487-77a3ba7ddc35.png)

Line 20 of `docs.scss` doesn't seem to have any strange characters. I deleted it and re-typed the line just to be sure. Here is what that section of the file looks like:

![image](https://cloud.githubusercontent.com/assets/1382445/15660121/4d2df87e-268c-11e6-9828-16059c66d16c.png)

**Comment by L-A** [comment]
@mikewheaton Thanks for the report! Seems like it's upstream from SASS, as described in [this issue](https://github.com/sass/sass/issues/189).

Since in my case I have control over Ruby's environment, I'll see about setting the `Encoding.default_external` to UTF-8 to make files default to it.

If you put `@charset "UTF-8";` at the top of your file, does this symptom go away by any chance?

**Comment by mikewheaton** [comment]
Unfortunately no, adding `@charset "UTF-8";` to the top of my `docs.scss` file didn't prevent the error from occurring. I also tried adding that to the top of the individual files that are being included with no luck. The build works fine so it's really not an issue.

If you'd like me to try a build with `Encoding.default_external` set to UTF-8 I'm happy to give it a try.

**Comment by L-A** [comment]
Alright, thanks for trying it out. I'll give you a heads up once I've made the fix available in a test build :)

**Comment by L-A** [comment]
Hi @mikewheaton!

I've finally recreated the issue locally and found a kosher way to fix it  – the latest version of Traveling Jekyll enforces UTF-8 as a default.

Give me a heads up if it fixes the issue on your side too: https://github.com/L-A/Little-Jekyll/releases/tag/0.1.4

**Comment by L-A** [comment]
Ninja-closing this as it's considered fixed. Feel free to report if the error pops up again :)
