### ISSUE TITLE
Installation fails on Node 6.3.0

### ISSUE THREAD

**Issue by nwootton** [L-A/Little-Jekyll#8]
Error thrown when npm install is run on OSX El-Capitan. Node install via homebrew and is up-to-date

``` bash
Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! little-jekyll@0.1.2 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the little-jekyll@0.1.2 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the little-jekyll package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs little-jekyll
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls little-jekyll
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /blog/Little-Jekyll/npm-debug.log
```

[npm-debug.log.zip](https://github.com/L-A/Little-Jekyll/files/363491/npm-debug.log.zip)

**Comment by L-A** [comment]
Hey @nwootton, thanks for the report!

I'll see about reproducing on my side. A quick glance tells me a React dependency (transition) might be the culprit:

`702 warn react-addons-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.`

**Comment by L-A** [comment]
Okay. I updated the necessary dependencies (that means Electron 1.0, so I'll be watchful before it goes into the main branch).

There's a branch available over at [update/node-6](https://github.com/L-A/Little-Jekyll/tree/update/node-6). You can pull it and it should build the same as `master` if you're running Node 6.x.

**Comment by nwootton** [comment]
Ok - I'll give it a try next time the Boss wants a Jekyll build!

**Comment by L-A** [comment]
Oh!

@nwootton If you simply want the app, head over to https://github.com/L-A/Little-Jekyll/releases, the builds are available :)
